### ISSUE TITLE
Add labels to piechart

### ISSUE THREAD

**Issue by ruzkant** [pepstock-org/Charba#1]
Firstly thanks for this project! I relate to the reasons for starting it...

On to the labels issue... I tried to use the java plugin code to render labels on a piechart using this bar chart example:
https://github.com/pepstock-org/Charba-Showcase/blob/master/src/org/pepstock/charba/showcase/client/samples/VerticalBarPluginLabelView.java

But for pie chart, x and y is always the same value, and I can't find a way to figure out how the arcs are going to place it differently with that plugin.

This seems to be a common question for chart.js and there is an external plugin for this:
https://github.com/emn178/Chart.PieceLabel.js/

Demo here will illustrate:
https://emn178.github.io/Chart.PieceLabel.js/samples/demo/

My jsinterop knowledge is rather limited, and so maybe you can give an example of how one would integrate an external javascript plugin?

Or maybe you have a simple java way you can think of for doing this?

**Comment by stockiNail** [comment]
@ruzkant I've commited in ShowCase project (in my branch "stock") an example how to use Piecelabel plugin.

What done?

1. I got the Chart.PieceLabel.js and store in my project into folder [resource/js](https://github.com/pepstock-org/Charba-Showcase/tree/stock/src/org/pepstock/charba/showcase/client/resources/js).

2. Charba is expecting that the options of a plugin are located in a object called "plugins". The PieceLabel plugin no! Therefore I've change the 168 of the plugin from

`` 
var pieceLabel =  chartInstance.options.pieceLabel;
`` 

to 

`` 
var pieceLabel =  chartInstance.options.plugins.piecelabel;
`` 

**Pay attention** that this plugin is not following a guideline about plugin to use. Chart.js recommends that the plugin ID can't contain uppercase letters. 

3. I've created a [Client Bundle](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/resources/Resources.java) to get the JS plugin

4. I've created an [Injector](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/Injector.java) to load the JS plugin into page.

5. I've created a GWT [Javascript object](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/samples/PieceLabelOptions.java),with some properties to configure PieceLabel

6. I've created my [view](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/samples/PieceLabelView.java) with a PieChart with the following statement to activate the plugin:

```java
PieceLabelOptions option = new PieceLabelOptions();
option.setRender("percentage");
option.setPrecision(2);
option.setFontColor("white");
option.setFontSize(16);
		
try {
	chart.getOptions().getPlugins().setOptions(PieceLabelOptions.ID, option.getObject());
} catch (InvalidPluginIdException e) {
	new Toast("Invalid PlugiID!", Level.ERROR, e.getMessage()).show();
}
```

This is the result:

![piecelabel](https://user-images.githubusercontent.com/11741250/39595833-e13fe276-4f10-11e8-8a7c-4f59f6c62d6c.png)

The new code will be deployed as part of Charba showcase soon!

**Comment by ruzkant** [comment]
@stockiNail Thanks so much!!! This will be very useful in reusing Chart.js community resources.

Here is my working sample:

![image](https://user-images.githubusercontent.com/20489132/39613113-52c0a85a-4f65-11e8-8d14-ff9388965dc3.png)

Much appreciated!

I am not sure if I should close the item or if you want to do some more things before doing that, so leaving it open, but I consider it closed for my case.

**Comment by stockiNail** [comment]
@ruzkant  Thank you too!

This issue is remembering me that I have to implement a way to load and use whatever JS plugin of Chart.js by Charba. I'm gonna close the issue when I'll commit this feature.

New feature should implement:

1. Ignore uppercase of Plugin ID (even if it is a best practice of Chart.js)
2. Add the plugin configuration in whatever configuration object (not only into "plugins") like options, axes, datasets and so on.
3. Provide a common way to import the JS by ClientBundle or by HTTP (if you don't want to maintain it in the project)
 4. Anything else to enable it....

**Comment by ruzkant** [comment]
Sounds good. I am just happy to have something in the meantime :)

I am trying to get rid of google charts. I use the GWT Material Design project for the UI widgets and they are shifting to amcharts, which is free only with a link to their site on every chart. My needs are relatively simple for now, and this is working well so far. The responsive option works reasonable well so far as well.

**Comment by ruzkant** [comment]
I notice you posted an issue on gwt material, so you know the project. I gave you a mention in the gwt material gitter channel: https://gitter.im/GwtMaterialDesign/gwt-material

**Comment by stockiNail** [comment]
I'm using GWT Material as well and Charba is working well.
I have seen the integration with amcharts but I don't like to put any link on my application.
That's why I developed Charba! ;)
Of course I'm aware that some features are still missing but I'm gonna develop them asap!

**Comment by stockiNail** [comment]
@ruzkant I've committed in ["stock" branch](https://github.com/pepstock-org/Charba/tree/stock) some improvements to use external java script plugins into Charba.

The improvements are:

1. You don't need Injector class specific for every plugin. The [Injector](https://github.com/pepstock-org/Charba/blob/stock/src/org/pepstock/charba/client/Injector.java) class of Charba can add a script (by ClientBundle and TextResource)
2. to load the script by HTTP from GWT is not a good idea because is async. If you don't want to add the script of plugin into the project, you should add it into  HTML page by <script> HTML element. 
3. A [Merger](https://github.com/pepstock-org/Charba/blob/stock/src/org/pepstock/charba/client/commons/Merger.java) utility class has been created to add a java script object in another one. In our case this enables to add the plugin configuration in any other configuration object of Charba. PieceLabel needs into options... some others use the "plugins" object into options.
4. I haven't removed the check about plugin and uppercase. But with above updates, we can use PieceLabel plugin as is, without any modification.

Let me come back about the usage. I've committed always in ["stock" branch](https://github.com/pepstock-org/Charba-Showcase/tree/stock) of Charba_Showcase how to use the above updates.

These are the steps:

1. take the [Chart.PieceLabel.js](https://raw.githubusercontent.com/emn178/Chart.PieceLabel.js/master/src/Chart.PieceLabel.js) plugin and store in the project into resource folder (see [here](https://github.com/pepstock-org/Charba-Showcase/tree/stock/src/org/pepstock/charba/showcase/client/resources/js))
2. Create a Client Bundle to get the JS plugin (see [here](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/resources/Resources.java))
3. use Charba Injector to inject the plugin. Here the example in the [main class](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/Charba_Showcase.java) of Charba ShowCase
```java
Injector.ensureInjected(Resources.INSTANCE.pieceLabelJsSource());
```
4. Create a GWT Javascript object, with some properties to configure the plugin (see [here](https://github.com/pepstock-org/Charba-Showcase/blob/stock/src/org/pepstock/charba/showcase/client/samples/PieceLabelOptions.java))
5. Create the view with a PieChart with the following statement to activate the plugin:
```java
PieceLabelOptions option = new PieceLabelOptions();
option.setRender("percentage");
option.setPrecision(2);
option.setFontColor("white");
option.setFontSize(16);

Merger.merge(chart.getOptions(), option, PieceLabelOptions.ID);
```

The updates are not merged to the master. Soon we will create a new release.

**Comment by ruzkant** [comment]
Thanks will have a look...

**Comment by stockiNail** [comment]
@ruzkant New plugins injection/integration has been deployed into new version [1.4](https://github.com/pepstock-org/Charba/releases/tag/1.4).

**Comment by ruzkant** [comment]
Thanks @stockiNail will migrate and see how it goes...

**Comment by ruzkant** [comment]
@stockiNail I have upgraded to 1.4 and my charts are still working. Appreciate the quick response and detailed instructions. Thanks!

**Comment by stockiNail** [comment]
@ruzkant FYI we decided to include out of the box `labels` [CHART.JS plugin](https://github.com/emn178/chartjs-plugin-labels) (former pieceLables) in Charba (next version, 2.1), with all configuration and callback properties. Hopefully can be useful.

**Comment by ruzkant** [comment]
@stockiNail Thanks. My project is on hold for a bit unfortunately, but when I get a chance I'd like to upgrade to not let it become stale...
