### ISSUE TITLE
Integration of chartjs-plugin-zoom

### ISSUE THREAD

**Issue by ezpzlmnsqz1337** [pepstock-org/Charba#28]
I would like to use https://github.com/chartjs/chartjs-plugin-zoom. I followed the [Plugins](https://github.com/pepstock-org/Charba/wiki/Plugins#importing-existing-chartjs-plugins) chapter of how to import existing chartjs plugin.

Since the plugin in chartjs options has 2 fileds (**pan** and **zoom**), I thought I should create some parent options, that would then set the options to the children.

So I have created a class PanZoomOptions:
```
public final class PanZoomOptions extends NativeObjectContainer {

    public static final String ID = "chartjs-plugin-zoom";

    private enum Property implements Key {
        pan, zoom
    }

    public PanZoomOptions() {
        this(null);
    }

    PanZoomOptions(NativeObject nativeObject) {
        super(nativeObject);
    }

    public void setPan(PanOptions pan) {
        setValue(Property.pan, pan);
    }

    public void setZoom(ZoomOptions zoom) {
        setValue(Property.zoom, zoom);
    }
}
```

Then I have created ZoomOptions class:
```
public final class ZoomOptions extends NativeObjectContainer {

    public static final String ID = "zoom";

    private enum Property implements Key {
        enabled, drag, mode
    }

    public ZoomOptions() {
        this(null);
    }
 
    ZoomOptions(NativeObject nativeObject) {
        super(nativeObject);
    }

    public void setEnabled(boolean enabled) {
        setValue(Property.enabled, enabled);
    }

    public void setMode(String mode) {
        setValue(Property.mode, mode);
    }

    public void setDrag(boolean drag) {
        setValue(Property.drag, drag);
    }
}
```

And very simillar class PanOptions.

Then I ensured I inject the TextResource with the JS of the plugin basically in onModuleLoad().
```
Injector.ensureInjected();
Injector.ensureInjected(GlobalResources.INSTANCE.chartZoomPlugin());
```
And finally in the presenter where I setup the chart I have added:
```
PanOptions panOptions = new PanOptions();
panOptions.setEnabled(true);
panOptions.setMode("xy");

ZoomOptions zoomOptions = new ZoomOptions();
zoomOptions.setEnabled(true);
zoomOptions.setDrag(false);
zoomOptions.setMode("xy");

PanZoomOptions panZoomOptions = new PanZoomOptions();
panZoomOptions.setPan(panOptions);
panZoomOptions.setZoom(zoomOptions);

chart.getOptions().getPlugins().setOptions(PanZoomOptions.ID, panZoomOptions);
```

Unfortunatelly after all this, all I get is the chart not working with exception in the console:
`Caught exception: (TypeError) : Cannot read property 'enabled' of undefined`

Can you please tell me where am I wrong? I tried to step the code and I can see that plugins array is added to the chart options and I can see my values there. But from my understanding, it should just be in chart options, not plugins, so should this plugin be used differently?

Thanks

**Comment by ezpzlmnsqz1337** [comment]
Now I figured out, that I get the exception already when Injecting the library. I guess it is because it is looking for pan.enabled and for zoom.enabled properties, that should be directly in ChartOptions, not plugins.

Unfortunatlly I see that LineChart is connected with LineOptions, so I guess I need to create new chart to add those fields in its ChartOptions?

**Comment by stockiNail** [comment]
@ezpzlmnsqz1337  first of all, let me say that the zoom plugin is not compliant with CHART.JS rules for plugins implementation:

Form CHART.JS [doc](https://www.chartjs.org/docs/latest/developers/plugins.html#plugin-options)

> Plugin options are located under the options.plugins config and are scoped by the plugin ID: options.plugins.{plugin-id}

This plugin is adding additional config directly at options level. But ok, let's try to do working as well.

If you are suing Charba version 2.0, there is a method to add objects to chart options:

```java
PanOptions panOptions = new PanOptions();
panOptions.setEnabled(true);
panOptions.setMode("xy");

ZoomOptions zoomOptions = new ZoomOptions();
zoomOptions.setEnabled(true);
zoomOptions.setDrag(false);
zoomOptions.setMode("xy");

chart.getOptions().merge(option, PanOptions.ID);
chart.getOptions().merge(option, ZoomOptions.ID);

```

`PanZoomOptions` is not needed because zoom and pan are properties of chart option (the root is chart options itself).

In version 2.1, we removed this method because plugins should be compliant with CHART.JS, but there is another way to do it.

Extends LineOptions adding plugin objects:

```java
public class ZoomOptions extends LineOptions {
	
	private enum Property implements Key {
		pan, zoom
	}

	public ZoomOptions(AbstractChart<?, ?> chart, ChartOptions defaultValues) {
		super(chart, defaultValues);
	}
	
	public void setPan(PanOptions pan) {
		setValue(Property.pan, pan);
	}

	public void setZoom(ZoomOptions zoom) {
		setValue(Property.zoom, zoom);
	}

}
```

Extends LineChart creating ZoomChart:

```java
public class ZoomLineChart extends LineChart {
	
	private final ZoomOptions options;

	public ZoomLineChart() {
		options = new ZoomOptions(this, getDefaultChartOptions());
	}

	@Override
	public ZoomOptions getOptions() {
		return options;
	}

}
```

Then inject plugin:

```java
Injector.ensureInjected();
Injector.ensureInjected(GlobalResources.INSTANCE.chartZoomPlugin());
```

Now in your code or UIBinder you can use ZoomLineChart. It's a workaround. The best thing would be to ask to the developers of plugin to be compliant with CHART.JS rule, reading options.[pluginid] instead of the elements into chart options.

Let me know if it works

**Comment by ezpzlmnsqz1337** [comment]
Unfortunately setValue() method is not available when extending LineOptions. The only method that makes sense is getConfiguration(), which returns ExtendedOptions. But from there setValue() is not visible again. :(


Since the plugin is referenced in chartjs docs, I thought it is a valid plugin. Now I can see that they even have opened issue for moving the settings into the plugins object.

**Comment by stockiNail** [comment]
You are completely right.. Sorry maybe yesterday night I was a little tired..
Nevertheless, if you are not using features of version 2.1, you could try to use version 2.0, where the merge methods was available.
I was also evaluating if make sense to reimplement in next version, to address these cases

**Comment by ezpzlmnsqz1337** [comment]
Well I kinda solve it by editing the chartjs-zoom-plugin to be able to get its settings from both, the root options and the plugin options. I also made a pull request there.

It just seems weird to me, that it is under the creator "chartjs" on github and they have their settings in the wrong place.

**Comment by stockiNail** [comment]
@ezpzlmnsqz1337 yes, that's correct. Nevertheless I was thinking to find a workaround to this issue we can re-implement the merge method as well.

We had the same issues for  another plugin which is not following the guidelines.
I did the same you did I took the plugin and I changed. The problem here is who will maintain the evolution. IF they don't change the plugin is in charge of you and of course that's not the best.

If you agree, we can again that method to have the workaround waiting for the community update of the plugin.
I agree with you that's a little strange but sometimes the people are developing something without mantaing it.

**Comment by ezpzlmnsqz1337** [comment]
Yea, but I made a pull request and they seem to accept it (after some minor [comments ](https://github.com/chartjs/chartjs-plugin-zoom/pull/217)), so this plugin will change.

But yea, maybe it wouldn't hurt Charba, if user would be able to add custom properties directly to the ChartOptions. But I think we can close this issue, since I solved my problem.

**Comment by stockiNail** [comment]
Yeah, that's what want to re-implement in the next version because makes sense. I would like do not close this issue because I'm gonna to close when I'll commit the merge method.

Another point of attention about zoom plugin. It adds a method to chart object to reset zoom `chart.resetZoom()`.

Be aware that the chart native object, that Charba maps, does not have this method. Therefore if you need, you should implement by javascript, maybe by a static method, injecting it (like you did with plugin itself).

**Comment by stockiNail** [comment]
MERGE methods added to all configuration containers.

**Comment by stockiNail** [comment]
@ezpzlmnsqz1337 we are thinking to include chart.js zoom plugin into Charba, out of the box, with all capabilities, in next release, as done for datalabels.

I have understood you did already many things on that. 

I would like to have your opinion, if you can.

**Comment by stockiNail** [comment]
@ezpzlmnsqz1337 we started developing the CHART.JS zoom plugin extensions.

Hopefully soon we can publish into the master the implementation.
