### ISSUE TITLE
Charba 2.0 with IE11

### ISSUE THREAD

**Issue by ak80** [pepstock-org/Charba#29]
I am trying to upgrade from charba 1.7 to 2.0 as I am looking forward to using some of the new and exiting features!

In our project we use GWT 2.8.2 and the gwt-maven-plugin from net.ltgt.gwt.maven. 

Everything works perfect in Chrome so far, but unfortunately we need to support Internet Explorer 11 and I get a TypeError on the console when calling setData()

```
	public void setData(double... values) {
		setArrayValue(Property.data, ArrayDouble.of(values));
	}

```

The exception happens on the setArrayValue() and says "Unable to get property 'apply' of undefined or null reference"

In the IE debugger is see that values is not null and all elements in the array have valid values. I seem to be unable to step in any further.

Can this problem be related to JsInterop which we have not used before?

**Comment by stockiNail** [comment]
@ak80 ak80 it could be Jsinterop. Let me test again in IE11 even if all versions are tested on Chrome, Firefox and IE (and Edge). 

About setData, you got the error setting data into data set. Could you tell me which type?
Are you using some specific features ?

Just to recreate the environment close to yours during test.
Thank you!

**Comment by ak80** [comment]
This happens with *BarDataset*, "*LineDataSet* and *DoughnutDataset*. We call *setData()* and supply and array of *double*.

Is that what you were looking for?

As for options, I do not see anything I think is special

```
    BarChart chart = new BarChart();
    chart.setWidth("100%");
    chart.getOptions().getLayout().getPadding().setTop(16);
    chart.getOptions().getLayout().getPadding().setBottom(32);

    chart.getOptions().setResponsive(true);
    chart.getOptions().setMaintainAspectRatio(false);
    chart.getOptions().getLegend().setDisplay(false);
    // here we format the tooltips
    chartFormatter.formatTooltips(chart.getOptions().getTooltips());

    BarDataset dataSet = chart.newDataset();
    dataSet.setBackgroundColor(getColor(i, report.numberOfSeries()));
    dataSet.setData(report.getSeries(i));
    ...
```

**Comment by stockiNail** [comment]
@ak80 yes, thank you very much.

I have tested right now with IE11 and I don't have any issue.

Let me take more time to do some other tests. 

Maybe you can test, using your IE11, the showcase [here](http://www.pepstock.org/Charba-Showcase/Charba_Showcase.html) where setData is always used.

**Comment by stockiNail** [comment]
@ak80 Can you try to use Charba version 2.1? We have changed the methods to load an array in new version to avoid null pointer exception

**Comment by stockiNail** [comment]
After a long journey, I was able to reproduce the error. Now I'm going in deep

**Comment by stockiNail** [comment]
@ak80 first of all, let me say the issue is related to JSINTEROp is leveraging on ES6 but IE 11 should USE  ES5.

There is a polyfill project called Polyfill.io API that can polyfill ES6 code client side.

If you add the following HTML statement in your GWT HTML page,  your charts should work:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```

<img width="939" alt="ie11" src="https://user-images.githubusercontent.com/11741250/53926886-573db280-4085-11e9-8a16-4c740d7bfbe0.png">

**Comment by ak80** [comment]
Wow, this is awesome. No, you are awesome! Again, for the second time you have not only helped me out but have done so in such a fast time. I am really impressed with Charba, and the quality of your showcases, but is even better :) Thank you so much.

Is there anything I can do to support you or the project?

**Comment by stockiNail** [comment]
Thank you very much, really appreciated!!

About your question, I don't know... at the moment, if you can, use it !! That's the best result for me. And thank you again,

Feel free  to contribute by pull requests or ideas or issues or anything you think could improve Charba. Whatever thing.  That's another very important part for me because different points of view improve everything.

`Coding is art`

**Comment by ssamikk** [comment]
Using polyfill in such a context certainly solves the problem, but the main idea of ​​charba is lost. We cannot use this library without an internet connection

**Comment by stockiNail** [comment]
@ssamikk you are right and I fully agree. Nevertheless polyfill is needed only for aged browser and in my opinion it's just a workaround. And I personally donìt like the polyfill concept because is adding tons of things and maybe not all needed.

Honestly I'm still investigating to solve the issue having a polyfill available without any internet connection, maybe embedded but I'm still looking for something efficient.

**Comment by stockiNail** [comment]
@ssamikk let me thank you in advance. With your post you gave me a good point to address.

Let me tell you in next version, a polyfill instance will be embedded in Charba and no internet connection will be needed anymore even using IE 11 or aged browser.

I have spent last hour to see more in deep Babel and then CoreJS. I have done some test with CoreJS (I don't know why I didn't find some weeks ago when I was looking for... I'm getting old) embedded in Charba and it works on IE11 without any connection or script URL into web page.

Now I have to improve the implementation. CoreJS is 152kb minified. I have added it as deferred load but maybe I can check (sencond phase) what really JSInterop needs in terms of additional javascript methods in order to include only what needed.

I'm opening again this issue in order to be aligned when the CoreJS will be avaialble into master and then usable.
 
@ssamikk  What do you think?

**Comment by stockiNail** [comment]
@ssamikk after some thoughts, I think that to have [corejs](https://github.com/zloirock/core-js) into Charba could be a solution but probably not the most efficient, also from user perspective.

This is needed only to who has got users with aged browsers and therefore to include it into Charba could not be the right way. Furthermore Charba could be included in other GWT frameworks which can have own polyfill. 

Nevertheless , to solve the issue without internet connection, it should be enough to have corejs (or another polyfill) in own GWT application. I have tested the Charba showcase which has got currently the  HTML script tag in order to get polyfill by internet (as described above in this issue).

The following items describe how to do (I'm gonna report them into `getting started` wiki page):

1.  Get [corejs](https://github.com/zloirock/core-js) by [this official link](https://unpkg.com/core-js-bundle@3.6.1/minified.js), the complete bundle (see the [installation section](https://github.com/zloirock/core-js#installation) where the bundle link is mentioned)
2. Save the minified corejs file in your project, for instance in your WAR folder, the same folder of GWT html page.
3. Add the following html script tag in you web page, in the `head` section, before loading your GWT application (replacing the polyfill statement as described above in this issue):

```html
    <script src="corejs.min.js"></script>
```
In this way you have polyfill, Charba is working and no internet connection.
We are going to change our showcase in order to get polyfill (corejs) into the project as example to who needs the same.

**Comment by stockiNail** [comment]
Added a [small section](https://github.com/pepstock-org/Charba/wiki/GettingStarted#polyfilling-your-gwt-project) into Getting Started wiki page trying to explain a couple of ways to activate `polyfill` for aged browsers.

**Comment by ssamikk** [comment]
Thanks for your reply. But for myself, I already solved the problem by redefining the two methods that I lacked (Array.from, Array.of). Polyfill for these functions took from the site with a description of these functions
