### ISSUE TITLE
Charba and Internet Explorer (11)

### ISSUE THREAD

**Issue by MartinSchwarzbauer** [pepstock-org/Charba#81]
Hi *!

I have to support aged browsers :( !
Now I have the problem, that IE 11 doesn't show our GWT webpage ... when I disable all the Charba stuff, UI is shown! 

I've found this (old) help: https://github.com/pepstock-org/Charba/issues/29
Adding polyfill, or corejs.js ... doesn't solve my problems! The webpage is still not shown correctly.

Is there still a way to support Charba / Charts in IE11 or at least load page :) 
I use the Charba tables in Ui:Binder and I think this is the problem when the page is loaded, the source will create error and won't show up!

Any solutions? Or just handle the IE stuff in source (just inject charba and add Tables to DOM when !IE)

Thank you,
Martin

**Comment by stockiNail** [comment]
@MartinSchwarzbauer Unfortunately Charba dropped the support of IE11 from version [4.0](https://github.com/pepstock-org/Charba/releases/tag/4.0) because the support has been dropped by CHART.jS in version 3 as well. For some capabilities, polyfill can be helpful but not for CHART.JS. I think it could be better to remove polyfill doc part because could be misleading.

**Comment by MartinSchwarzbauer** [comment]
Ok thank you very much for your answer!

**Comment by stockiNail** [comment]
@MartinSchwarzbauer apologize... :(
